#!/usr/bin/perl

use v5.40;

use NGCP::Cleanup;

my $config_file = '/etc/ngcp-cleanup-tools/acc-cleanup.conf';

my $c;
try {
    $c = NGCP::Cleanup->new(config_file => $config_file);
    $c->process;
} catch ($e) {
    $c->error($e);
    $c->env('dbh')->disconnect if $c->env('dbh');
}

exit 0;
